require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'faceshieldedge' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :flipper_configuration => FlipperConfiguration.disabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # FaceShield dependencies
  pod 'react-native-vision-camera',   :path => '../node_modules/react-native-vision-camera'
  pod 'react-native-fast-tflite',     :path => '../node_modules/react-native-fast-tflite'
  pod 'react-native-mmkv',            :path => '../node_modules/react-native-mmkv'
  pod 'RNKeychain',                   :path => '../node_modules/react-native-keychain'
  pod 'RNCNetInfo',                   :path => '../node_modules/@react-native-community/netinfo'

  # TFLite framework (via CocoaPods)
  pod 'TensorFlowLiteSwift', '~> 2.14.0'
  pod 'TensorFlowLiteSwift/CoreML', '~> 2.14.0'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Enable CoreML delegate for TFLite
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
